---
- name: generate nginx conf
  template:
    src: nginx.conf.j2
    dest: "{{ dest }}/nginx/{{ envv }}.conf"
    mode: "0644"

- name: nginx test
  command: docker-compose exec nginx_{{ envv }} nginx -t
  become: true
  become_method: sudo
  args:
    chdir: "{{ dest }}"
    removes: "{{ dest }}/nginx/{{ envv }}.conf"
  register: result

- name: debug nginx -t
  debug:
    var: result.stdout

- name: reload nginx
  command: docker-compose exec nginx_{{ envv }} nginx -s reload
  become: true
  become_method: sudo
  args:
    chdir: "{{ dest }}"
  when: "'successful' in result.stdout"

- name: restart docker-compose
  docker_compose:
    project_src: "/opt/docker-{{ envv }}"
    services: "nginx_{{ envv }}"
    restarted: yes
